### ISSUE TITLE
help

### ISSUE THREAD

**Issue by EnderBoi201** [TML233/UndertaleEngine#111]
___________________________________________
############################################################################################
ERROR in
action number 1
of Other Event: Game Start
for object world:

Error defining an external function.
 at gml_Script_Console_Init (line 8) -               global._gmu_console_function_init=external_define(dll,"Init",call,ty_real,0);
############################################################################################
gml_Script_Console_Init (line 8)
gml_Object_world_Other_2 (line 3) - Console_Init();

**Comment by TML233** [comment]
It is already fixed, download the latest master branch.
