### ISSUE TITLE
About compatibility

### ISSUE THREAD

**Issue by SansPapyrus** [TML233/UndertaleEngine#112]
Games developed with this engine won't run on Windows 11.
(I'm a Chinese, may I use Chinese Simplified here?)

**Comment by Ceyase** [comment]
Running is possible on Windows 11. Why can't you run it?. Please show log.

**Comment by SansPapyrus** [comment]
当时它闪退了。而现在它似乎又可以正常运行了，但是仍然有一些问题。比如蓝魂状态下的跳跃的效果不同

**Comment by SansPapyrus** [comment]
当时它闪退了。而现在它似乎又可以正常运行了...
可能是当时我使用了Windows 11 Canary.
抱歉。
