### ISSUE TITLE
Resource checks breaks due to GameMaker updating resource types.

### ISSUE THREAD

**Issue by Ceyase** [TML233/UndertaleEngine#119]
# Premise
In the latest GameMaker Runtime (2023.8.1.148), the resource type will no longer be **Real**, so the following code will not work.
```
var font = font_add(path,size,bold,italic,first,last);
show_debug_message(is_real(font));
// Output: False
```
The type of all resources (e.g. Font) becomes ref. however we don't have a function like is_ref.
So we need to use the exist function directly.

# Impacts

Lang series functions all fail (except Lang_GetString).
Button sprites all become black and white error textures.
Battle system fails because _enemy is Real.

---

I will make a PR to fix the BUG.

**Comment by TML233** [comment]
#126 fixed this.
