### ISSUE TITLE
Save files break when inserting new objects.

### ISSUE THREAD

**Issue by TML233** [TML233/UndertaleEngine#121]
Save file breaks due to object index reordering, such as items, phones and battle fight panels.

Add a string to resource id mapping.
When saving save files, convert the resource id to string.
When loading save files, convert string to resource id.

**Comment by Animeliqite** [comment]
Changing the fight target object flag to a string worked for me (I then used `asset_get_index` to convert the string into an asset)

**Comment by TML233** [comment]
There's two ways to approach this: let the user register the mapping manually or just use the object name.
Items might have a major redesign later, utilizing the new struct feature.

**Comment by SheepYhangCN** [comment]
This should be fixed by GameMaker's update since resources are `handle` instead of `real` now
If you `string()` it, it won't show a number as before
(I can't confirm it since I replaced save file with `object/room_get_name` long time ago, so it needs to be confirm)

**Comment by SheepYhangCN** [comment]
> This should be fixed by GameMaker's update since resources are `handle` instead of `real` now If you `string()` it, it won't show a number as before (I can't confirm it since I replaced save file with `object/room_get_name` long time ago, so it needs to be confirm)

ref can still be change after you added new resources
so this issue still be a issue
