### ISSUE TITLE
Language system.

### ISSUE THREAD

**Issue by EMpustSamE** [TML233/UndertaleEngine#147]
Even we can load fonts of different languages,but not strings.So I hope the Lang can be updated that can load strings of different languages.

**Comment by SheepYhangCN** [comment]
Actually, most strings in UTE are loaded from localization system
You can check https://github.com/TML233/UndertaleEngine/tree/master/datafiles/locale/english/string
To get a string from locale, use `Lang_GetString`

**Comment by EMpustSamE** [comment]
I mean that is there any way to load strings from other folders in locale?(Just like datafiles/spanish/string)

**Comment by SheepYhangCN** [comment]
Add a new language folder in `datafiles/locale`
Then add the folder name in `datafiles/locale/list.txt` as new line
Everytime you change language, just execute `Lang_LoadFont/Sprite/String`
You can use language folder name or lines(0 means line 1) as argument to load

**Comment by EMpustSamE** [comment]
oh thanks

**Comment by SheepYhangCN** [comment]
If there aren't any problem further, I'm gonna close this issue
Re-open is welcome any time.
