### ISSUE TITLE
The border didn't changed the window's width and the pixels are kinda broken.

### ISSUE THREAD

**Issue by Animeliqite** [TML233/UndertaleEngine#3]
![image](https://user-images.githubusercontent.com/39384772/55278073-be632580-5318-11e9-8ee9-f756f70101cb.png)

I don't know why it's happening, I don't know if it's a bug or something but how do I fix it?

**Comment by TML233** [comment]
Did you put a new camera instance in the room or something?

**Comment by Animeliqite** [comment]
No, I didn't. Let me put and see...

**Comment by Animeliqite** [comment]
Nope, the same error appeared again.

**Comment by TML233** [comment]
so did you change anything in the engine?

**Comment by Animeliqite** [comment]
No I didn't change anything.

**Comment by TML233** [comment]
weird, what's the version of your GMS2 IDE and Runtime?

**Comment by Animeliqite** [comment]
Let me see...

**Comment by Animeliqite** [comment]
IDE v2.2.0.343
Runtime v2.2.0.258

**Comment by TML233** [comment]
that's weird, everything goes well on my machine.
try to update your ide to v2.2.2.413, and the runtime to v2.2.2.326, re-fork and re-clone the repository.

**Comment by Animeliqite** [comment]
Okay.
Installing now.

**Comment by Animelici804** [comment]
Also your "a new hope" repository is public, I think you should make it private.

**Comment by HouJunhao33** [comment]
thanks, i will hide that later.

**Comment by Animeliqite** [comment]
Thank you, it works now

**Comment by Animeliqite** [comment]
Also how's the documentation going on?

**Comment by Animeliqite** [comment]
![image](https://user-images.githubusercontent.com/39384772/55278294-6f6abf80-531b-11e9-853b-facb8e099a13.png)
Border has a problem too.

**Comment by TML233** [comment]
Working on it. Please be patient.

**Comment by Animeliqite** [comment]
Okay.

**Comment by TML233** [comment]
Use Border_SetSprite(sprite) to change the border.

**Comment by Animeliqite** [comment]
No I mean the window's width is not changed.

**Comment by Animeliqite** [comment]
Pixels are kinda broken in this image that I gave you.

**Comment by TML233** [comment]
Is the function window_set_size working?

**Comment by Animeliqite** [comment]
Let me see...

**Comment by Animeliqite** [comment]
![image](https://user-images.githubusercontent.com/39384772/55278357-45fe6380-531c-11e9-9da4-bfe57f608bb0.png)
Well, I couldn't find where it is.

**Comment by TML233** [comment]
The line of code that changes the size of the window is in the script Border_SetEnabled.

**Comment by TML233** [comment]
By the way, how did you enabled the border??

**Comment by Animeliqite** [comment]
I went to "border" object's create event. And I changed "_enabled=false" to "_enabled=true"

**Comment by Animeliqite** [comment]
Wait a minute... I found the solution.

**Comment by Animeliqite** [comment]
I need to activate the script. Also thanks for helping me.

**Comment by TML233** [comment]
Well, please use Border_SetEnabled(true) instead.
Please note there's a rule that the variable started with _ shouldn't be edited outside that object.

**Comment by TML233** [comment]
And if there is another problem, please open a new issue instead of editing the old issue.

**Comment by Animeliqite** [comment]
Okay.
