### ISSUE TITLE
[i18n] Add PNG bitmap fonts for a locale

### ISSUE THREAD

**Issue by Dobby233Liu** [TML233/UndertaleEngine#34]
I can't explain it clear, NVM my Engrish.

We can add TrueType fonts to the game for a locale like [this](https://github.com/TML233/undertale_engine/tree/master/datafiles/locale/english/font), but I wonder we can add bitmap fonts, that would be great.

**Comment by TML233** [comment]
我会做的（咕咕咕）

**Comment by Dobby233Liu** [comment]
@TML233 I'm just rushing you, I 100% believe you

**Comment by HEYimHeroic** [comment]
i actually had issues with changing the locale fonts, replacing the locale fonts with built-in fonts (like crypt_of_tomorrow) would be more convenient i think.
