### ISSUE TITLE
Player can have empty name.

### ISSUE THREAD

**Issue by Cetaceaqua** [TML233/UndertaleEngine#35]
**Please fix it.**(but how to give issue a tag?)

**Comment by Dobby233Liu** [comment]
But though that is a completely off-topic, Toby Fox uses a empty player name for the UndertaleDemo screenshots, so removing this feature (bug) is completely not useful for developer's quick review (this bug can be reused for debugging purpose)

**Comment by Cetaceaqua** [comment]
You're right.
(用中文吧我太懒了不想深究那些英语句子了)
不过捏已经在群里和糖萌芦说过了, 他说可以修复这个, 所以我发了这条issue.
还有测试的问题, 糖萌芦的Console应该能够快速调用, 而且实在不行你就把房间放前面嘛, 直接跳过取名. =w=

**Comment by Dobby233Liu** [comment]
nvm

**Comment by Dobby233Liu** [comment]
And only Collaborators and Owner can add labels to issues.

**Comment by Cetaceaqua** [comment]
** So I only need to wait for TML, he'll add the tag, yeah~ **

**Comment by HEYimHeroic** [comment]
a quick fix for this would be to go to the name list and add/change an entry with the case of "", and have it as valid=false. give it a prefix name of "menu.confirm.title.nothing" or something. then in the menu.txt, add a "menu.confirm.title.nothing" entry with the text "Please enter a name." or something similar.
