### ISSUE TITLE
I don't want to be mean but, when will you update the engine?

### ISSUE THREAD

**Issue by Animeliqite** [TML233/UndertaleEngine#71]
I thought the schools are closed now in China, but it looks like the project is kinda cancelled...

**Comment by TML233** [comment]
im going to update a lot, so please be patient!

**Comment by Animeliqite** [comment]
by the way do you have discord?

**Comment by TML233** [comment]
TML #7851

**Comment by Animeliqite** [comment]
ok thanks

**Comment by Animeliqite** [comment]
sent you a friend request from Fortnitelici#3502

**Comment by Animeliqite** [comment]
please, accept my friend request... i changed my nick to doge
