### ISSUE TITLE
Wavy text for enemy dialogue

### ISSUE THREAD

**Issue by Animeliqite** [TML233/UndertaleEngine#72]
> The problem

In the battle system, I tried to make a wavy text by using...
`{effect 1}`
...but I can only make the text shaky...

> The solution

...so you can add a wavy text option and set the wavy text effect to `1` which will look like `{effect 1}`

Thanks for reading...

**Comment by onezhazha233** [comment]
sin and cos function can help you to make the text effect

**Comment by Animeliqite** [comment]
Yeah, it can help me but I don't know how to do sine and cosine function in GML language. Also, if I knew sines and cosines, it would require a lot of code changes in my opinion. Let's leave the job to TML. They know how their engine works.
