### ISSUE TITLE
Who to make a Battle System ?

### ISSUE THREAD

**Issue by RockiDOG** [TML233/UndertaleEngine#73]
I don't know who to create a battle who can help me ?

**Comment by Animeliqite** [comment]
https://tml233.github.io/undertale_engine/#/tutorial/battle/0_dummy
There's a documentation about how to create battles. If you have a Desktop license of Game Maker Studio 2, then you can easily use this engine.

**Comment by RockiDOG** [comment]
Yes but he doesn't have a sprite of the Dummy @Animelici804
And the tutorial is not completed
@TML233

**Comment by Animeliqite** [comment]
You can find the dummy sprite yourself. Just import the Dummy sprite, and then, if it's not scaled to `%200,` then scale it to `%200` percent, and finally, set the origin to the bottom-center. After doing all of this, set your enemy object's sprite to the dummy. You don't have to always make a dummy.

**Comment by Animeliqite** [comment]
I know, I know, it's really hard to be patient for waiting for an Undertale engine to be done. You also gotta be patient. TML is making this engine and the documentation as fast as possible.

**Comment by RockiDOG** [comment]
And for the Ennemy attack ? The Bullet ?

**Comment by Animeliqite** [comment]
I couldn't figure out how to make a bullet.

**Comment by RockiDOG** [comment]
Oh ;-;

**Comment by RockiDOG** [comment]
A Battle with no attack ;-;

**Comment by Animeliqite** [comment]
Maybe, in the future, TML will write how that works.

**Comment by RockiDOG** [comment]
Maybe ;;-;;

**Comment by BabyGolden2** [comment]
Want me to find out how?

**Comment by Animeliqite** [comment]
well it would be good, thanks

**Comment by jevilhumor** [comment]
@RockiDOG 
[organized.zip](https://github.com/TML233/undertale_engine/files/3564057/organized.zip)
Well, if you need organized UNDERTALE sprites, heres ya go!

**Comment by TML233** [comment]
Simple battle example updated, checkout the example branch to learn more.
