### ISSUE TITLE
Will there be a Deltarune Engine in future?

### ISSUE THREAD

**Issue by Animeliqite** [TML233/UndertaleEngine#75]
I am the creator of this fangame: [Link to the fangame](https://gamejolt.com/games/deltarunechapter2/383992) and I need a Deltarune Engine for my game to not to be cancelled. I really have my dreams for my Deltarune Chapter 2 fangame, and I really want to not to be cancelled. Please, make my dreams true, @TML233 .

**Comment by Dobby233Liu** [comment]
TML may working on it already.
edit:
![1561812325708](https://user-images.githubusercontent.com/28653235/60384671-f2361e80-9ab2-11e9-980f-638b95da6266.png)
~dont leak tml's black stories~
~however no new info about that engine~

**Comment by Animeliqite** [comment]
Really? How do you know that?

**Comment by Dobby233Liu** [comment]
edited my first comment

**Comment by Animeliqite** [comment]
Maybe that's cancelled, that's why they're not making new updates to their Deltarune Engine.

**Comment by TML233** [comment]
Sorry, it is cancelled because the battle system of deltarune may be varied in the future.

**Comment by Dobby233Liu** [comment]
@TML233 then you can make deltarune chapter 1 engine, because you say chapter 2 can be vary, then chapter 1 wont. (but i think better no, youre already too busy, you could even not keeping the files)

**Comment by Animeliqite** [comment]
yeah that's right, toby said that he will release all the chapters years and years later.

**Comment by Animeliqite** [comment]
@Dobby233Liu where is TML's twitter site, i couldn't find it, could you give me TML's twitter link?

**Comment by Dobby233Liu** [comment]
> @Dobby233Liu where is TML's twitter site, i couldn't find it, could you give me TML's twitter link?

He even don't have Twitter, bud.
