### ISSUE TITLE
Some missing features in a one post.

### ISSUE THREAD

**Issue by Animeliqite** [TML233/UndertaleEngine#88]
Hello again, TML. I'm still looking forward to your UNDERTALE engine. Good job! You literally revive almost all of the fan-games.

I'm now here to tell you what's wrong or missing in your engine in a one post.

* **The music inside the naming screen.**
   Yes, the naming screen and the menu is looking pretty original, but we're missing the music. In UNDERTALE, you may know that **when we meet or date monsters, the music will have one more instrument**. I know, I could add it myself too, but who knows? Maybe you will do it in a different way.
![image](https://user-images.githubusercontent.com/39384772/65822138-cb20f180-e247-11e9-9f7f-016717a23f62.png)
* **More information in Documentation.**
   There's a really good information in your documentation, but all of the information are less, and that's why I needed to learn your UNDERTALE engine by looking at the codes. What if I'm doing things wrong? I even want to learn making animations with `GMU_Anim` scripts.
![image](https://user-images.githubusercontent.com/39384772/65822204-8a75a800-e248-11e9-9028-1f33e3e6e6b1.png)
* **All of the possible cutscene examples in the example branch.**
   Making cutscenes are really hard for me, because I sometimes mess it up; like, the game spawns an object every miliseconds.
![image](https://user-images.githubusercontent.com/39384772/65822258-9c0b7f80-e249-11e9-8b52-91e10eb35e27.png)
* **Wavy text in any of the textboxes.**
  In UNDERTALE, all of the monsters except mini-bosses and bosses use wavy text in the bubble dialogues. So I think that this is really important for the battles.
![image](https://user-images.githubusercontent.com/39384772/65822281-0cb29c00-e24a-11e9-93b0-2af8e0eb9a0b.png) 
(Screenshot was taken from a game called True Genocide made by Soup Taels 😒)

**Comment by friedplugstudios** [comment]
heya. for no. 1, just put a music command in the creation code of the room. or make a separate object entirely, with a room start command that plays the music, and a room end command that ends the music.
for no. 2, it states that it's usually updated, and since the project literally just go back online, i wouldn't really care. i just got started with this engine, and i don't know how to do anything.
for no. 3, you can just look up a wavy text tutorial.
easy as pie.

however, i would like an in-depth explanation on how this engine works, TML. maybe some attacks, damage, how to make items, and such.

**Comment by Animeliqite** [comment]
The wavy effects are not easy for me though. Trigonometry is almost all over the wavy text code. I don't even know trigonometry, and I only know substructures of the goddamn math. Math is really hard.

**Comment by onezhazha233** [comment]
Write "siner = 0" after the creation code in the text_single object, and replace the code in the pre draw:
```
switch(effect){
	case -1:
		_offset_x=0;
		_offset_y=0;
		break;
		
	case 0:
		if(_effect_shook){
			_offset_x=random_range(-1,1);
			_offset_y=random_range(-1,1);
		}
		_effect_shook=!_effect_shook;
		break;
		
	case 1:
		siner += 1;
		_offset_x=sin(siner/10)*2;
		_offset_y=cos(siner/10)*2;
		break;
}
```

*but do not press "x" or "shift" to skip the text.

**Comment by Animeliqite** [comment]
Oh and @TML233 , you forgot to do the story of Undertale in your game.

**Comment by onezhazha233** [comment]
> Oh and @TML233 , you forgot to do the story of Undertale in your game.

he said,he cancelled this game

**Comment by Animeliqite** [comment]
I mean in the engine.

**Comment by Dobby233Liu** [comment]
> Oh and [@]TML233 , you forgot to do the story of Undertale in your game.

ya mean the intro storytelling part? ~~i believe it's once a to-do~~ (<i style="color:grey">it isn't</i>)

**Comment by Animeliqite** [comment]
Yeah @Dobby233Liu .
