### ISSUE TITLE
NOT AN ISSUE, just a suggestion

### ISSUE THREAD

**Issue by jevilhumor** [TML233/UndertaleEngine#89]
Just finished trying out your DELTARUNE v.s. Susie game, and I'm thoroughly impressed you managed to fit all of that into one object. So, I was wondering if you'd be interested in making a DELTARUNE engine for GameMaker. You obviously understand how to, so why don't you try it? You'd be the first to ever do it. (btw i was impressed enough to follow you, good job! :)

**Comment by Animeliqite** [comment]
Yes, I would like that one as well, but TML is determined about waiting for all of the chapters. He could make an engine for chapter one but he's still determined about it. It would at least help my dead fan-game.

**Comment by Dobby233Liu** [comment]
related: #75, and https://github.com/TML233/undertale_engine/issues/88#issuecomment-536807003 (zhazha mean Inheritale I leaked in https://github.com/TML233/undertale_engine/issues/75#issuecomment-506953706)
